// <auto-generated />
using System;
using Investry.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investry.Persistence.Migrations
{
    [DbContext(typeof(InvestryDbContext))]
    [Migration("20260502202703_AddSupportTickets")]
    partial class AddSupportTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("CategoryProject");
                });

            modelBuilder.Entity("Investry.Domain.Entities.CapitalReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapitalReturnStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("InvestmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MudarabahConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ReturnedAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CapitalReturnStatus");

                    b.HasIndex("InvestmentId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("MudarabahConfigId");

                    b.ToTable("CapitalReturn");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f0a28a-723a-4a6c-9a4a-2e38c3e3e3e3"),
                            Description = "Projects related to software, hardware, and internet services.",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("c1d5e8f0-1a2b-3c4d-5e6f-7a8b9c0d1e2f"),
                            Description = "Projects in the medical, wellness, and health tech fields.",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Description = "Creative projects including film, music, design, and visual arts.",
                            Name = "Art & Culture"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-b7c8-d9e0-f1a2b3c4d5e6"),
                            Description = "Restaurants, food products, and innovative culinary ventures.",
                            Name = "Food & Beverage"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-d7e8-f9a0-1b2c3d4e5f6a"),
                            Description = "Educational tools, platforms, and learning resources.",
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-e7f8-a9b0-1c2d3e4f5a6b"),
                            Description = "Projects focused on sustainability, conservation, and green technology.",
                            Name = "Environment"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-f7a8-9b0c-1d2e3f4a5b6c"),
                            Description = "Clothing, accessories, and innovative fashion-related projects.",
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("Investry.Domain.Entities.EquityConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EquityPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("EquityConfigs");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulProjects")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RewardTierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RewardTierId");

                    b.HasIndex("InvestorId", "RewardTierId")
                        .IsUnique()
                        .HasFilter("[RewardTierId] IS NOT NULL");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("Investry.Domain.Entities.InvestorProfitAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AllocatedProfit")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CapitalRatio")
                        .HasColumnType("decimal(18,10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("InvestmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProfitDistributionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("ProfitDistributionId");

                    b.ToTable("InvestorProfitAllocations");
                });

            modelBuilder.Entity("Investry.Domain.Entities.InvestorShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountInvested")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquityConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("SharesPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EquityConfigId");

                    b.HasIndex("InvestmentId")
                        .IsUnique();

                    b.HasIndex("InvestorId");

                    b.ToTable("InvestorShares");
                });

            modelBuilder.Entity("Investry.Domain.Entities.MudarabahConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("InvestorsProfitSharePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MudarabahEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MudarabahStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfitDistributionFrequency")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("MudarabahConfigs");
                });

            modelBuilder.Entity("Investry.Domain.Entities.ProfitDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DistributedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributionStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("FounderProfit")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("InvestorsPoolProfit")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MudarabahConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DistributionStatus");

                    b.HasIndex("MudarabahConfigId");

                    b.ToTable("ProfitDistributions");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FundingModel")
                        .HasColumnType("int");

                    b.Property<int>("FundingPolicy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MinimumContribution")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<string>("PromotionalVideoURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.HasIndex("Title", "FounderId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Investry.Domain.Entities.ProjectMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMedia");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("RewardConfigs");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxBackers")
                        .HasColumnType("int");

                    b.Property<Guid>("RewardConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RewardConfigId", "Title")
                        .IsUnique();

                    b.ToTable("RewardTiers");
                });

            modelBuilder.Entity("Investry.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Investry.Domain.Entities.SystemWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("SystemWallets");
                });

            modelBuilder.Entity("Investry.Domain.Entities.SystemWalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InvestmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SystemWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InvestmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SystemWalletId");

                    b.ToTable("SystemWalletTransactions");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("FounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FounderId")
                        .IsUnique()
                        .HasFilter("[FounderId] IS NOT NULL");

                    b.HasIndex("InvestorId")
                        .IsUnique()
                        .HasFilter("[InvestorId] IS NOT NULL");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Investry.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Investry.Domain.Entities.CapitalReturn", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Investment", "Investment")
                        .WithMany()
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Investor", "Investor")
                        .WithMany("CapitalReturns")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.MudarabahConfig", "MudarabahConfig")
                        .WithMany("CapitalReturns")
                        .HasForeignKey("MudarabahConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Investment");

                    b.Navigation("Investor");

                    b.Navigation("MudarabahConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.EquityConfig", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithOne("EquityConfig")
                        .HasForeignKey("Investry.Domain.Entities.EquityConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investment", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Investor", "Investor")
                        .WithMany("Investments")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithMany("Investments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.RewardTier", "RewardTier")
                        .WithMany("Investments")
                        .HasForeignKey("RewardTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Investor");

                    b.Navigation("Project");

                    b.Navigation("RewardTier");
                });

            modelBuilder.Entity("Investry.Domain.Entities.InvestorProfitAllocation", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Investment", "Investment")
                        .WithMany()
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Investor", "Investor")
                        .WithMany("ProfitAllocations")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.ProfitDistribution", "ProfitDistribution")
                        .WithMany("InvestorProfitAllocations")
                        .HasForeignKey("ProfitDistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");

                    b.Navigation("Investor");

                    b.Navigation("ProfitDistribution");
                });

            modelBuilder.Entity("Investry.Domain.Entities.InvestorShare", b =>
                {
                    b.HasOne("Investry.Domain.Entities.EquityConfig", "EquityConfig")
                        .WithMany("InvestorShares")
                        .HasForeignKey("EquityConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Investment", "Investment")
                        .WithOne()
                        .HasForeignKey("Investry.Domain.Entities.InvestorShare", "InvestmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Investor", "Investor")
                        .WithMany("InvestorShares")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquityConfig");

                    b.Navigation("Investment");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("Investry.Domain.Entities.MudarabahConfig", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithOne("MudarabahConfig")
                        .HasForeignKey("Investry.Domain.Entities.MudarabahConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.ProfitDistribution", b =>
                {
                    b.HasOne("Investry.Domain.Entities.MudarabahConfig", "MudarabahConfig")
                        .WithMany("ProfitDistributions")
                        .HasForeignKey("MudarabahConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MudarabahConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Founder", "Founder")
                        .WithMany("Projects")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("Investry.Domain.Entities.ProjectMedia", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithMany("Media")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithOne("RewardConfig")
                        .HasForeignKey("Investry.Domain.Entities.RewardConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.HasOne("Investry.Domain.Entities.RewardConfig", "RewardConfig")
                        .WithMany("RewardTiers")
                        .HasForeignKey("RewardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.SystemWalletTransaction", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Investment", "Investment")
                        .WithMany()
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Investry.Domain.Entities.SystemWallet", "SystemWallet")
                        .WithMany("Transactions")
                        .HasForeignKey("SystemWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investment");

                    b.Navigation("Project");

                    b.Navigation("SystemWallet");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Founder", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Investry.Domain.Entities.Wallet", "FounderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Investry.Domain.Entities.Investor", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Investry.Domain.Entities.Wallet", "InvestorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Investry.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Investry.Domain.Entities.EquityConfig", b =>
                {
                    b.Navigation("InvestorShares");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Founder", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investor", b =>
                {
                    b.Navigation("CapitalReturns");

                    b.Navigation("Investments");

                    b.Navigation("InvestorShares");

                    b.Navigation("ProfitAllocations");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Investry.Domain.Entities.MudarabahConfig", b =>
                {
                    b.Navigation("CapitalReturns");

                    b.Navigation("ProfitDistributions");
                });

            modelBuilder.Entity("Investry.Domain.Entities.ProfitDistribution", b =>
                {
                    b.Navigation("InvestorProfitAllocations");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.Navigation("EquityConfig");

                    b.Navigation("Investments");

                    b.Navigation("Media");

                    b.Navigation("MudarabahConfig");

                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.Navigation("RewardTiers");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.Navigation("Investments");
                });

            modelBuilder.Entity("Investry.Domain.Entities.SystemWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
