// <auto-generated />
using System;
using Investry.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investry.Persistence.Migrations
{
    [DbContext(typeof(InvestryDbContext))]
    [Migration("20260326010942_LinkFounderProject")]
    partial class LinkFounderProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investry.Domain.Entities.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulProjects")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FundingModel")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.HasIndex("Title", "FounderId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("RewardConfigs");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxBackers")
                        .HasColumnType("int");

                    b.Property<Guid>("RewardConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RewardConfigId");

                    b.ToTable("RewardTiers");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Founder", "Founder")
                        .WithMany("Projects")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithOne("RewardConfig")
                        .HasForeignKey("Investry.Domain.Entities.RewardConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.HasOne("Investry.Domain.Entities.RewardConfig", "RewardConfig")
                        .WithMany("RewardTiers")
                        .HasForeignKey("RewardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Founder", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.Navigation("RewardTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
