// <auto-generated />
using System;
using Investry.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investry.Persistence.Migrations
{
    [DbContext(typeof(InvestryDbContext))]
    [Migration("20260404145319_AddEquityConfigsTable")]
    partial class AddEquityConfigsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investry.Domain.Entities.EquityConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompanyValuation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EquityPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("EquityConfigs");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulProjects")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RewardTierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RewardTierId");

                    b.HasIndex("InvestorId", "RewardTierId")
                        .IsUnique()
                        .HasFilter("[RewardTierId] IS NOT NULL");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("Investry.Domain.Entities.InvestorShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountInvested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquityConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SharesPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EquityConfigId");

                    b.HasIndex("InvestmentId")
                        .IsUnique();

                    b.HasIndex("InvestorId");

                    b.ToTable("InvestorShare");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FundingModel")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.HasIndex("Title", "FounderId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("RewardConfigs");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaxBackers")
                        .HasColumnType("int");

                    b.Property<Guid>("RewardConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RewardConfigId", "Title")
                        .IsUnique();

                    b.ToTable("RewardTiers");
                });

            modelBuilder.Entity("Investry.Domain.Entities.EquityConfig", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithOne("EquityConfig")
                        .HasForeignKey("Investry.Domain.Entities.EquityConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investment", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Investor", "Investor")
                        .WithMany("Investments")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.RewardTier", "RewardTier")
                        .WithMany()
                        .HasForeignKey("RewardTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Investor");

                    b.Navigation("Project");

                    b.Navigation("RewardTier");
                });

            modelBuilder.Entity("Investry.Domain.Entities.InvestorShare", b =>
                {
                    b.HasOne("Investry.Domain.Entities.EquityConfig", "EquityConfig")
                        .WithMany("InvestorShares")
                        .HasForeignKey("EquityConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Investment", "Investment")
                        .WithOne()
                        .HasForeignKey("Investry.Domain.Entities.InvestorShare", "InvestmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investry.Domain.Entities.Investor", "Investor")
                        .WithMany("InvestorShares")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquityConfig");

                    b.Navigation("Investment");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Founder", "Founder")
                        .WithMany("Projects")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.HasOne("Investry.Domain.Entities.Project", "Project")
                        .WithOne("RewardConfig")
                        .HasForeignKey("Investry.Domain.Entities.RewardConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardTier", b =>
                {
                    b.HasOne("Investry.Domain.Entities.RewardConfig", "RewardConfig")
                        .WithMany("RewardTiers")
                        .HasForeignKey("RewardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.EquityConfig", b =>
                {
                    b.Navigation("InvestorShares");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Founder", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Investor", b =>
                {
                    b.Navigation("Investments");

                    b.Navigation("InvestorShares");
                });

            modelBuilder.Entity("Investry.Domain.Entities.Project", b =>
                {
                    b.Navigation("EquityConfig");

                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Investry.Domain.Entities.RewardConfig", b =>
                {
                    b.Navigation("RewardTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
